# Generated by Django 5.2.9 on 2025-12-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_patient_date_of_birth_patient_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='main_app.appointment'),
        ),
    ]
