# Generated by Django 5.2.9 on 2025-12-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_report_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
    ]
