# Generated by Django 5.2.9 on 2025-12-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_report_doctor_remove_report_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='main_app.appointment'),
        ),
    ]
